x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
a1= x & y #Bitwise AND 
a2= x | y #Bitwise OR 
a3= ~x #Bitwise NOT 
a4=x ^ y # Bitwise XOR 
a5=x >> 2 # >> Bitwise right shift 
a6=x<<2 #<<Bitwise left shift 
print( "bitwise AND=",a1) 
print( "bitwise OR=",a2) 
print( "bitwise NOT=",a3) 
print( "bitwise XOR=",a4) 
print( "bitwise Right shift=",a5) 
print( "bitwise Left shift=",a6) 
